class OCRLanguage:
  Arabic = "ara"
  Bulgarian = "bul"
  Simplified_Chinese = "chs"
  Traditional_Chinese = "cht"
  Croatian = "hrv"
  Czech = "cze"
  Danish = "dan"
  Dutch = "dut"
  English = "eng"
  Finnish = "fin"
  French = "fre"
  German = "ger"
  Greek = "gre"
  Hungarian = "hun"
  Korean = "kor"
  Italian = "ita"
  Japanese = "jpn"
  Polish = "pol"
  Portuguese = "por"
  Russian = "rus"
  Slovenian = "slv"
  Spanish = "spa"
  Swedish = "swe"
  Turkish = "tur"

  languages = ["ara", "bul", "chs", "cht", "hrv", "cze", "dan", "dut", "eng", "fin", "fre", "ger", "gre", "hun", "kor", "ita", "jpn", "pol", "por", "rus", "slv", "spa", "swe", "tur"]